[6493] ChatGPT Plugin instructions via Search and Install Plugin broken reference errors
craftercms/chatgpt-plugin pull request #3
Opened 2024-01-31 15:37 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6493

2024-01-31 15:38 UTC, jvega190 commented
@rart I updated the README to use the url for the raw images just as we do for the plugin preview image

2024-01-31 16:01 UTC, sumerjabri requested changes
Please update the version numbers so we can publish it.

2024-01-31 16:32 UTC, jvega190 commented
@sumerjabri version updated

2024-02-01 13:38 UTC, sumerjabri approved these changes

2024-02-01 13:38 UTC, merged